[package]
name = "governance"
edition = "2024.beta"
version = "0.0.6"
published-at = "0x3a3babecdd13b588c29fcd854819fc79f050ac7a7919b41d24ba66ab21dc1de3"
[dependencies]
Sui = { local = "/home/naru/my_apps/nasun-devnet/sui/crates/sui-framework/packages/sui-framework" }

[addresses]
governance = "0x0"

[environments]
devnet = "272218f1"
nasun-devnet = "272218f1"
