[package]
name = "governance"
edition = "2024.beta"
version = "0.0.4"
published-at = "0xf6d2c99985eec548a604d7d49491b36a76fd02d7ac37e3cab11b8609797186fc"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/devnet" }

[addresses]
governance = "0x0"

[environments]
nasun-devnet = "6681cdfd"
