const fs = require("fs");
const path = require("path");

const ARTIFACT_PATH = path.join(
  __dirname,
  "..",
  "artifacts",
  "contracts",
  "NasunGenesisPass.sol",
  "NasunGenesisPass.json"
);

const OUTPUT_DIR = path.join(
  __dirname,
  "..",
  "..",
  "..",
  "frontend",
  "src",
  "constants"
);

function main() {
  if (!fs.existsSync(ARTIFACT_PATH)) {
    console.error("Artifact not found. Run 'pnpm compile' first.");
    process.exit(1);
  }

  const artifact = JSON.parse(fs.readFileSync(ARTIFACT_PATH, "utf8"));
  const abi = artifact.abi;

  // Load deployment addresses if available
  const deploymentsDir = path.join(__dirname, "..", "deployments");
  const addresses = {};

  if (fs.existsSync(deploymentsDir)) {
    for (const file of fs.readdirSync(deploymentsDir)) {
      if (file.endsWith(".json")) {
        const data = JSON.parse(fs.readFileSync(path.join(deploymentsDir, file), "utf8"));
        addresses[data.chainId] = data.address;
      }
    }
  }

  const output = `// Auto-generated by copy-abi.cjs - do not edit manually
// Run: cd apps/nasun-website/contracts/genesis-pass && pnpm copy-abi

export const GENESIS_PASS_ABI = ${JSON.stringify(abi, null, 2)} as const;

export const GENESIS_PASS_ADDRESSES: Record<number, string> = ${JSON.stringify(
    Object.fromEntries(
      Object.entries(addresses).map(([k, v]) => [Number(k), v])
    ),
    null,
    2
  )};
`;

  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  const outputPath = path.join(OUTPUT_DIR, "genesis-pass-contract.ts");
  fs.writeFileSync(outputPath, output);
  console.log("ABI + addresses written to:", outputPath);
}

main();
