[package]
name = "baram"
edition = "2024"
version = "0.0.1"

[dependencies]
pado_tokens = { local = "/home/naru/my_apps/nasun-monorepo/apps/pado/contracts" }

[addresses]
baram = "0x0"

[environments]
devnet = "12bf3808"
nasun-devnet = "12bf3808"
