[package]
name = "pado_perp"
edition = "2024"
version = "0.0.1"
published-at = "0xe0b972913d44d1c214d02ccf0aaf64d1c0d7ab075a7caaaf1fc457c486c808b1"

[dependencies]
Sui = { local = "/home/naru/my_apps/nasun-devnet/sui/crates/sui-framework/packages/sui-framework" }
devnet_tokens = { local = "../../../packages/devnet-tokens" }
pado_oracle = { local = "../contracts-oracle" }

[addresses]
pado_perp = "0x0"

[environments]
devnet = "272218f1"
nasun-devnet = "272218f1"
