[package]
name = "pado_perp"
edition = "2024"
version = "0.0.1"
published-at = "0x6821a73cfc3cd45dc6318db379c2c88f0acb61ec6a26060f4de8cbe4718d3658"

[dependencies]
Sui = { local = "/home/naru/my_apps/nasun-devnet/sui/crates/sui-framework/packages/sui-framework" }
devnet_tokens = { local = "../../../packages/devnet-tokens" }

[addresses]
pado_perp = "0x0"

[environments]
devnet = "272218f1"
nasun-devnet = "272218f1"
