[package]
name = "nasun_smart_account"
edition = "2024"
version = "0.1.0"
published-at = "0x097e96d5e0c09915b6ba2ed744fe2d4ee0bd21df1d453e6528d4d82c96c1c44b"

[dependencies]
Sui = { local = "<NASUN_DEVNET>/sui/crates/sui-framework/packages/sui-framework" }

[addresses]
nasun_smart_account = "0x0"

[environments]
devnet = "272218f1"
nasun-devnet = "272218f1"
