// Bundle src/server.ts -> dist/server.mjs (single self-contained ESM file, all deps inlined: hono,
// @hono/node-server, postgres, jose, @mysten/sui). Preserves the box "scp one server.mjs" deploy contract
// used by the sibling identity-compute / leaderboard / referral / issuer services. Run from this dir:
// `node build.mjs`. Resolves esbuild from the monorepo root node_modules (root has esbuild 0.27.x).
//
// OUTPUT IS dist/server.mjs (untracked build artifact), scp'd to /srv/nasun/address-book/server.mjs on the box.

import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));

const banner = {
  js: '// GENERATED by build.mjs from src/*.ts -- do NOT edit by hand. Source of truth: src/.\n'
    + '// nasun-address-book bundle. Rebuild: `node build.mjs`.\n'
    + "import { createRequire as __nodeCreateRequire } from 'node:module';\n"
    + 'const require = __nodeCreateRequire(import.meta.url);',
};

await build({
  entryPoints: [resolve(here, 'src/server.ts')],
  outfile: resolve(here, 'dist/server.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  minify: false, // keep readable for box-side audit
  banner,
  legalComments: 'none',
  logLevel: 'info',
});
console.log('[build] wrote dist/server.mjs');
