[package]
name = "pado_lottery"
edition = "2024"
version = "0.0.1"
published-at = "0xeb5af6c536464672cc6975b07957ff222037c724a4f2810b0cd295bb8b4304da"

[dependencies]
devnet_tokens = { local = "../../../packages/devnet-tokens" }

[addresses]
lottery = "0x0"

[environments]
devnet = "272218f1"
nasun-devnet = "272218f1"
