[package]
name = "pado_lottery"
edition = "2024"
version = "0.0.1"
published-at = "0xd56f405af7127a15e30a5104ec91574a7483699e5ac1d74383ed5478aee43900"

[dependencies]
devnet_tokens = { local = "../../../packages/devnet-tokens" }

[addresses]
lottery = "0x0"

[environments]
devnet = "272218f1"
nasun-devnet = "272218f1"
