[package]
name = "pado_lottery"
edition = "2024"
version = "0.0.1"
published-at = "0x5605eda3794c1701a15f5fe0ee8ecae0fcb7529490db38544a0d865658d0dc43"

[dependencies]
devnet_tokens = { local = "../../../packages/devnet-tokens" }

[addresses]
lottery = "0x0"

[environments]
devnet = "272218f1"
nasun-devnet = "272218f1"
