packages:
  - 'apps/*'
  - 'apps/*/frontend'
  - 'apps/*/chat-server'
  - 'apps/*/scripts'
  - 'apps/*/executor-nitro'
  - 'apps/*/api-server'
  - 'packages/*'
  # deepbookv3는 별도 관리 (외부 라이브러리)
  - '!apps/pado/deepbookv3'
