[package]
name = "devnet_tokens"
edition = "2024"
version = "0.0.1"
published-at = "0x1c93579be99e89ab05a33ac04af2fd7b1a604f9c98fe74d1b6cae6913c8362e7"

[dependencies]
Sui = { local = "/home/naru/my_apps/nasun-devnet/sui/crates/sui-framework/packages/sui-framework" }

[addresses]
devnet_tokens = "0x96adf476d488ffb588d0bfdb5c422355f065386a2e7124e66746fb7078816731"

[environments]
devnet = "272218f1"
nasun-devnet = "272218f1"
