[package]
name = "devnet_tokens_v2"
edition = "2024"
version = "0.0.1"

[dependencies]
Sui = { local = "/home/naru/my_apps/nasun-devnet/sui/crates/sui-framework/packages/sui-framework" }

[addresses]
devnet_tokens_v2 = "0x0"

[environments]
devnet = "272218f1"
nasun-devnet = "272218f1"
