[package]
name = "nasun_tier"
edition = "2024"
version = "0.0.1"
published-at = "0x1b1f684bbc6795461ad5fba6e13427ec8ccbf2921aaa555a15f4aac827f0f7b9"

[dependencies]
# Sui and std are implicit system dependencies in the new package system

[addresses]
nasun_tier = "0x1b1f684bbc6795461ad5fba6e13427ec8ccbf2921aaa555a15f4aac827f0f7b9"

[environments]
devnet = "272218f1"
nasun-devnet = "272218f1"
