#!/usr/bin/env bash
# nasun_points delta-sync (AWS-exit Stage 2 §6.1 / §9.1 / §12 watermark gate).
#
# Keeps the box copy of nasun_points current with the LIVE node-3 source for the append-only,
# bigint-id-sequence ledgers (the irrecoverable crown-jewel data: activity_points cannot be
# recomputed from chain -- memory project_2026_06_09_points_offaws_backup). The bulk was restored
# 2026-06-06/07; this script carries the delta since then and on every run.
#
# Mechanism (per append-only table): box_max = max(id) on box; pull rows from node-3 WHERE id >
# box_max via COPY TO STDOUT, stream into box via COPY FROM STDIN. The watermark guarantees pulled
# rows are new (no PK conflict); COPY is transactional (a failed run rolls back wholly -> box_max
# unchanged -> re-run is identical). Additive + idempotent + READ-ONLY on node-3 (live serving
# untouched; explorer-api keeps owning node-3 until Stage 4 cutover).
#
# NOT covered here (follow-on): mutable current-state tables (user_nsi, nft_health_state,
# staking_emission_state, player_stats ...) = recomputed by the scanners post-lift, and
# date-snapshot tables (ecosystem_*_scores/snapshots, weekly_*, *_daily_snapshots) = settled, need
# a date-watermark pass. Those are lower urgency (derived/settled). This pass covers the
# source-of-truth event ledgers.
#
# Usage:
#   NODE3_SSH='ssh -i <key> ubuntu@<node3-host>' \
#   BOX_SSH='ssh -i <key> nasun@<box-host>' \
#   ./nasun-points-delta-sync.sh [--dry-run]
# Infra identifiers (hosts, key paths) are NOT hardcoded -- this repo is public, so the source
# (node-3) and target (box) SSH commands are supplied via env (e.g. an operator-local, gitignored
# .env or the nasun-ops private wrapper). Both must reach `sudo -u postgres psql nasun_points`.
set -euo pipefail

: "${NODE3_SSH:?set NODE3_SSH (the source/live ssh prefix, e.g. 'ssh -i ~/.ssh/key ubuntu@<node3-host>')}"
: "${BOX_SSH:?set BOX_SSH (the target/box ssh prefix, e.g. 'ssh -i ~/.ssh/key nasun@<box-host>')}"
N3_SSH="$NODE3_SSH"
BOX_SSH="$BOX_SSH"
N3_PSQL="sudo -u postgres psql nasun_points"
BOX_PSQL="sudo -u postgres psql nasun_points"

# Two sync modes (verified 2026-06-12). Schemas verified equal box==node-3.
#  INCREMENTAL "schema.table:watermark_col" -- append-only with a single monotonic key; pull WHERE
#    col > box_max(col). Used for the big irrecoverable ledgers (cheap to keep fresh).
#  FULL "schema.table" -- TRUNCATE box + COPY all from node-3; always-correct, for composite-key /
#    small tables where an incremental watermark is unsafe (dup/miss risk).
# Schemas: activity_points/snapshot_change_log/vault_* = public; game_round/bankroll_event/crash_*/
# lottery_* = gostop. NOTE the box copy is a staging replica (explorer-api serves node-3 until Stage 4
# cutover), so a brief empty window during a FULL refresh is harmless.
#
# NOT synced here (deliberate): derived/recomputable tables (ecosystem_*/weekly_*/*_daily_snapshots =
# settled snapshots; user_nsi/nft_health_state/staking_emission_state/player_stats/*_daily matviews =
# regenerated by the scanners). Those carry no data-survival value (recomputable) and are refreshed by
# a full dump+restore or scanner re-run at cutover, not continuously.
SYNC_INC="public.activity_points:id gostop.game_round:id gostop.bankroll_event:id public.snapshot_change_log:id gostop.crash_round:round_id gostop.lottery_round:round_number"
SYNC_FULL="gostop.crash_cashout gostop.lottery_ticket public.vault_trades public.vault_flows public.vault_fee_events"
DRY=0; [ "${1:-}" = "--dry-run" ] && DRY=1

echo "=== nasun_points delta-sync $([ $DRY -eq 1 ] && echo '(DRY RUN)') $(date -u +%FT%TZ) ==="
echo "--- INCREMENTAL (watermark) ---"
for E in $SYNC_INC; do
  T="${E%%:*}"; WM="${E##*:}"
  # watermark value quoted as a literal -> works for bigint and timestamp alike (implicit cast).
  BOXMAX=$($BOX_SSH "$BOX_PSQL -tAc \"SELECT COALESCE(max($WM)::text,'')  FROM $T\"")
  N3MAX=$($N3_SSH  "$N3_PSQL  -tAc \"SELECT COALESCE(max($WM)::text,'')  FROM $T\"")
  if [ -z "$BOXMAX" ]; then COND="true"; else COND="$WM > '$BOXMAX'"; fi
  DELTA=$($N3_SSH "$N3_PSQL -tAc \"SELECT count(*) FROM $T WHERE $COND\"")
  printf '[%s] wm=%s box_max=%s node3_max=%s delta=%s\n' "$T" "$WM" "$BOXMAX" "$N3MAX" "$DELTA"
  { [ "$DELTA" -eq 0 ] || [ $DRY -eq 1 ]; } && continue
  $N3_SSH "$N3_PSQL -c \"COPY (SELECT * FROM $T WHERE $COND ORDER BY $WM) TO STDOUT\"" \
    | $BOX_SSH "$BOX_PSQL -c \"COPY $T FROM STDIN\""
  printf '  -> synced; box_max now=%s\n' "$($BOX_SSH "$BOX_PSQL -tAc \"SELECT max($WM) FROM $T\"")"
done
echo "--- FULL (truncate+copy) ---"
for T in $SYNC_FULL; do
  BOXN=$($BOX_SSH "$BOX_PSQL -tAc 'SELECT count(*) FROM $T'")
  N3N=$($N3_SSH  "$N3_PSQL  -tAc 'SELECT count(*) FROM $T'")
  printf '[%s] box_rows=%s node3_rows=%s\n' "$T" "$BOXN" "$N3N"
  [ $DRY -eq 1 ] && { echo "  (dry-run: would TRUNCATE+COPY $N3N rows)"; continue; }
  [ "$BOXN" = "$N3N" ] && { echo "  (rows equal; skip)"; continue; }
  $BOX_SSH "$BOX_PSQL -c 'TRUNCATE $T'"
  $N3_SSH "$N3_PSQL -c \"COPY (SELECT * FROM $T) TO STDOUT\"" | $BOX_SSH "$BOX_PSQL -c \"COPY $T FROM STDIN\""
  printf '  -> refreshed; box_rows now=%s\n' "$($BOX_SSH "$BOX_PSQL -tAc 'SELECT count(*) FROM $T'")"
done
echo "=== done ==="
