/**
 * zkLogin Types for Sui blockchain
 *
 * zkLogin allows users to authenticate using OAuth providers (Google, Apple, etc.)
 * and derive a deterministic Sui address from their OAuth identity.
 */

/**
 * Supported OAuth providers for zkLogin
 */
export type ZkLoginProvider = 'google' | 'apple' | 'twitch' | 'facebook' | 'kakao';

/**
 * OAuth configuration for a provider
 */
export interface OAuthConfig {
  provider: ZkLoginProvider;
  clientId: string;
  redirectUri: string;
  scope?: string;
}

/**
 * Session data stored for zkLogin authentication
 * This is saved to sessionStorage to survive page navigation during OAuth flow
 */
export interface ZkLoginSession {
  /** Serialized ephemeral keypair (base64) */
  ephemeralPrivateKey: string;
  /** Random value used in nonce generation */
  randomness: string;
  /** Maximum epoch until the session expires */
  maxEpoch: number;
  /** OAuth nonce (derived from ephemeral pubkey, maxEpoch, randomness) */
  nonce: string;
  /** Timestamp when session was created */
  createdAt: number;
}

/**
 * zkLogin proof generated by the prover service
 */
export interface ZkLoginProof {
  proofPoints: {
    a: string[];
    b: string[][];
    c: string[];
  };
  issBase64Details: {
    value: string;
    indexMod4: number;
  };
  headerBase64: string;
}

/**
 * Complete zkLogin state after successful authentication
 */
export interface ZkLoginState {
  /** OAuth provider used */
  provider: ZkLoginProvider;
  /** JWT from OAuth provider */
  jwt: string;
  /** Salt for address derivation (from backend) */
  salt: string;
  /** Derived Sui address */
  address: string;
  /** Serialized ephemeral keypair (base64) */
  ephemeralPrivateKey: string;
  /** Ephemeral public key (base64) - used for validation */
  ephemeralPublicKey?: string;
  /** Maximum epoch until session expires */
  maxEpoch: number;
  /** Randomness used in nonce generation */
  randomness: string;
  /** ZK proof (generated by prover, null if not yet generated) */
  proof: ZkLoginProof | null;
  /** Address seed for signature generation */
  addressSeed: string;
  /** Unix timestamp when the state expires */
  expiresAt: number;
  /** User email from OAuth (if available) */
  email?: string;
  /** User name from OAuth (if available) */
  name?: string;
  /** User profile picture URL from OAuth (if available) */
  picture?: string;
}

/**
 * Response from the salt management API
 */
export interface SaltResponse {
  /** Hex-encoded salt */
  salt: string;
  /** Derived Sui address */
  address: string;
  /** Whether this is a new user */
  isNewUser: boolean;
  /** OAuth provider */
  provider: string;
  /** User email */
  email?: string;
  /** User name */
  name?: string;
  /** User profile picture URL */
  picture?: string;
}

/**
 * Prover API request parameters
 */
export interface ProverRequest {
  /** JWT from OAuth provider */
  jwt: string;
  /** Extended ephemeral public key (bigint string) */
  extendedEphemeralPublicKey: string;
  /** Maximum epoch */
  maxEpoch: number;
  /** JWT randomness */
  jwtRandomness: string;
  /** User salt */
  salt: string;
  /** Key claim name (usually 'sub') */
  keyClaimName: string;
}

/**
 * Prover API response
 */
export interface ProverResponse extends ZkLoginProof {
  /** Address seed for the derived address */
  addressSeed: string;
}

/**
 * zkLogin configuration
 */
export interface ZkLoginConfig {
  /** Salt API endpoint */
  saltApiUrl: string;
  /** ZK Prover endpoint (defaults to Mysten Labs prover) */
  proverUrl?: string;
  /** OAuth provider configurations */
  providers: Partial<Record<ZkLoginProvider, OAuthConfig>>;
}

/**
 * Error types specific to zkLogin
 */
export type ZkLoginErrorType =
  | 'OAUTH_CANCELLED'
  | 'JWT_EXPIRED'
  | 'JWT_INVALID'
  | 'SALT_FETCH_FAILED'
  | 'PROVER_FAILED'
  | 'SESSION_EXPIRED'
  | 'SIGNATURE_FAILED'
  | 'NONCE_MISMATCH'
  | 'PROVIDER_NOT_CONFIGURED';

/**
 * zkLogin specific error
 */
export class ZkLoginError extends Error {
  type: ZkLoginErrorType;

  constructor(type: ZkLoginErrorType, message: string) {
    super(message);
    this.type = type;
    this.name = 'ZkLoginError';
  }
}
