[package]
name = "baram_executor"
edition = "2024"
published-at = "0xac09c1d6540e29454ee98bc18a5fa8f29b1c343153c8edf7dd92edd296f2d1ff"

[dependencies]
# Sui and std are implicit system dependencies in the new package system

[environments]
devnet = "12bf3808"
nasun-devnet = "12bf3808"
