// src/constants/pageContent/products.ts
// 카테고리와 이모지 매핑
export const CATEGORY_EMOJIS: Record<string, string> = {
  Animation: "🎬",
  "Live-Action": "🎥",
  Movies: "🍿",
  "Multiplayer Shooter": "🔫",
  Strategy: "♟️",
  RPG: "⚔️",
  "Open World": "🗺️",
  "Sci-fi": "👽",
  Horror: "👻",
  Comedy: "😂",
  "Children's Content": "🧸", // 작은따옴표 통일
  "Children’s Content": "🧸", // 큰따옴표 버전 추가 (i18n에서 이 형태로 올 수 있음)
  Fantasy: "🧙",
  PC: "💻",
  Mobile: "📱",
  Web: "🌐",
  Streaming: "📺",
  Theatrical: "🎭",
  Dapps: "🖥️",
  Handhelds: "🎮",
  Metaverse: "🌌",
  "VR/AR/XR": "👓",
  "Mixed Reality": "🕶️",
  "Mixed Reality Centers": "🏢",
  "AI Driven": "🤖",
  Haptics: "🖐️",
  "Brain Interfaces": "🧠",
  UGC: "✍️",
  "Theme Parks": "🎢",
  Cybernetics: "🔌",
  Cyborgs: "🦾",
  Robots: "🤖",
  "Giant Robots": "🦿",
  "Real Life Giant Robot Arena Competitions": "⚔️",
  "Live Festivals": "🎪",
  "Digital Festivals": "🎆",
  "LFGO!": "🚀",
  Merchandise: "🛍️",
  Comics: "📚",
  "Graphic Novels": "🖼️",
  Novels: "📖",
  NFTs: "🖼️",
  Software: "💾",
  Hardware: "🔧",
  Spaceships: "🚀",
  Research: "🔬",
  "T-shirts": "👕",
  Mugs: "☕",
  Cards: "🃏",
};

export const KOREAN_TO_ENGLISH: Record<string, string> = {
  애니메이션: "Animation",
  실사: "Live-Action",
  영화: "Movies",
  "멀티플레이어 슈팅 게임": "Multiplayer Shooter",
  전략: "Strategy",
  RPG: "RPG",
  오픈월드: "Open World",
  공상과학: "Sci-fi",
  공포: "Horror",
  코미디: "Comedy",
  "어린이 콘텐츠": "Children's Content",
  판타지: "Fantasy",
  PC: "PC",
  모바일: "Mobile",
  웹: "Web",
  스트리밍: "Streaming",
  "극장 상영": "Theatrical",
  디앱: "Dapps",
  "휴대용 게임기": "Handhelds",
  메타버스: "Metaverse",
  "VR/AR/XR": "VR/AR/XR",
  "혼합 현실": "Mixed Reality",
  "혼합 현실 센터": "Mixed Reality Centers",
  "AI 구동": "AI Driven",
  햅틱: "Haptics",
  "브레인 인터페이스": "Brain Interfaces",
  UGC: "UGC",
  테마파크: "Theme Parks",
  사이버네틱스: "Cybernetics",
  사이보그: "Cyborgs",
  로봇: "Robots",
  "거대 로봇": "Giant Robots",
  "실제 거대 로봇 경기 대회": "Real Life Giant Robot Arena Competitions",
  "라이브 페스티벌": "Live Festivals",
  "디지털 페스티벌": "Digital Festivals",
  "LFGO!": "LFGO!",
  굿즈: "Merchandise",
  만화: "Comics",
  "그래픽 노블": "Graphic Novels",
  소설: "Novels",
  NFTs: "NFTs",
  소프트웨어: "Software",
  하드웨어: "Hardware",
  우주선: "Spaceships",
  연구: "Research",
  티셔츠: "T-shirts",
  머그컵: "Mugs",
  카드: "Cards",
};

export const INITIAL_VISIBLE_CATEGORIES = 48;
export const CHANGE_INTERVAL = 1500;
export const FLIP_INTERVAL = 1000;
