// src/constants/pageContent/products.ts
// 카테고리와 이모지 매핑
export const CATEGORY_EMOJIS: Record<string, string> = {
  Animation: "🎬",
  "Live-Action": "🎥",
  Movies: "🍿",
  "Multiplayer Shooter": "🔫",
  Strategy: "♟️",
  RPG: "⚔️",
  "Open World": "🗺️",
  "Sci-fi": "👽",
  Horror: "👻",
  Comedy: "😂",
  "Children's Content": "🧸", // 작은따옴표 통일
  "Children’s Content": "🧸", // 큰따옴표 버전 추가 (i18n에서 이 형태로 올 수 있음)
  Fantasy: "🧙",
  PC: "💻",
  Mobile: "📱",
  Web: "🌐",
  Streaming: "📺",
  Theatrical: "🎭",
  Dapps: "🖥️",
  Handhelds: "🎮",
  Metaverse: "🌌",
  "VR/AR/XR": "👓",
  "Mixed Reality": "🕶️",
  "Mixed Reality Centers": "🏢",
  "AI Driven": "🤖",
  Haptics: "🖐️",
  "Brain Interfaces": "🧠",
  UGC: "✍️",
  "Theme Parks": "🎢",
  Cybernetics: "🔌",
  Cyborgs: "🦾",
  Robots: "🤖",
  "Giant Robots": "🦿",
  "Real Life Giant Robot Arena Competitions": "⚔️",
  "Live Festivals": "🎪",
  "Digital Festivals": "🎆",
  "LFGO!": "🚀",
  Merchandise: "🛍️",
  Comics: "📚",
  "Graphic Novels": "🖼️",
  Novels: "📖",
  NFTs: "🖼️",
  Software: "💾",
  Hardware: "🔧",
  Spaceships: "🚀",
  Research: "🔬",
  "T-shirts": "👕",
  Mugs: "☕",
  Cards: "🃏",
};

export const INITIAL_VISIBLE_CATEGORIES = 48;
export const CHANGE_INTERVAL = 1500;
export const FLIP_INTERVAL = 1000;
