[package]
name = "baram_compliance"
edition = "2024"
version = "0.0.1"

[dependencies]
Sui = { local = "/home/naru/my_apps/nasun-devnet/sui/crates/sui-framework/packages/sui-framework" }

[addresses]
baram_compliance = "0x0"

[environments]
devnet = "12bf3808"
nasun-devnet = "12bf3808"
