[package]
name = "unified_margin"
edition = "2024"
version = "0.0.1"
published-at = "0x5bdbf3aaa5999674bea412f2dd7dce417a188343f7213cb7105d9c1eaacce31d"

[dependencies]
Sui = { local = "<NASUN_DEVNET>/sui/crates/sui-framework/packages/sui-framework" }
devnet_tokens = { local = "../../../packages/devnet-tokens" }

[addresses]
unified_margin = "0x0"

[environments]
devnet = "272218f1"
nasun-devnet = "272218f1"
