[package]
name = "unified_margin"
edition = "2024"
version = "0.0.1"
published-at = "0x1a1a6e86712a866e8bf7b2d6320b364282b5b257f8f9419db652914cf2d7a472"

[dependencies]
Sui = { local = "<NASUN_DEVNET>/sui/crates/sui-framework/packages/sui-framework" }
devnet_tokens = { local = "../../../packages/devnet-tokens" }
pado_oracle = { local = "../contracts-oracle" }

[addresses]
unified_margin = "0x1a1a6e86712a866e8bf7b2d6320b364282b5b257f8f9419db652914cf2d7a472"

[environments]
devnet = "272218f1"
nasun-devnet = "272218f1"
