[package]
name = "baram_aer"
edition = "2024"
version = "1.2.0"
published-at = "0x4437f360aacd9a4419172ed6d9c2e72f714181cdc68dc2a34ab9ee5fb84ccf6b"

[dependencies]
Sui = { local = "/home/naru/my_apps/nasun-devnet/sui/crates/sui-framework/packages/sui-framework", override = true }
MoveStdlib = { local = "/home/naru/my_apps/nasun-devnet/sui/crates/sui-framework/packages/move-stdlib", override = true }
baram = { local = "../contracts" }

[addresses]
baram_aer = "0x4437f360aacd9a4419172ed6d9c2e72f714181cdc68dc2a34ab9ee5fb84ccf6b"

[environments]
devnet = "272218f1"
nasun-devnet = "272218f1"
