[package]
name = "baram_aer"
edition = "2024"
version = "1.1.0"
published-at = "0x0c9f78fc8c91a1f26e5643d08c6ebce5a8ef43b2fcdbf658b1dfa70db466b164"

[dependencies]
Sui = { local = "/home/naru/my_apps/nasun-devnet/sui/crates/sui-framework/packages/sui-framework", override = true }
MoveStdlib = { local = "/home/naru/my_apps/nasun-devnet/sui/crates/sui-framework/packages/move-stdlib", override = true }
baram = { local = "../contracts" }

[addresses]
baram_aer = "0x0c9f78fc8c91a1f26e5643d08c6ebce5a8ef43b2fcdbf658b1dfa70db466b164"

[environments]
devnet = "272218f1"
nasun-devnet = "272218f1"
