// Bundle src/server.ts -> dist/server.mjs (single self-contained ESM file, all deps inlined: postgres,
// @mysten/sui/verify, ethers). Preserves the box "scp one server.mjs" deploy contract and removes the
// need for vendored node_modules. Run from this dir: `node build.mjs`.
//
// ★ OUTPUT IS dist/server.mjs (untracked build artifact), NOT the committed top-level server.mjs. During
// the C3a inert period the box still runs the committed hand-written C0/C1 server.mjs, so keeping the
// committed file unchanged preserves the repo==box invariant (and stops a shared-worktree session from
// deploying this inert bundle as "C1"). At the C3a cutover, scp dist/server.mjs to the box AND promote
// it to the committed server.mjs in the same step. The bundle is regenerable from src/ at any time.
//
// Resolves esbuild from the monorepo root node_modules (root has esbuild 0.27.x).

import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));

await build({
  entryPoints: [resolve(here, 'src/server.ts')],
  outfile: resolve(here, 'dist/server.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  minify: false, // keep readable for box-side audit of the security-critical bundle
  banner: {
    js: '// GENERATED by build.mjs from src/*.ts -- do NOT edit by hand. Source of truth: src/.\n'
      + '// nasun-identity-compute bundle (C3a). Rebuild: `node build.mjs`.',
  },
  legalComments: 'none',
  logLevel: 'info',
});

console.log('[build] wrote dist/server.mjs');
