// Bundle src/server.ts -> dist/server.mjs (single self-contained ESM file, deps inlined: openai,
// @mysten/sui). Preserves the box "scp one server.mjs" deploy contract used by the sibling
// referral / leaderboard / address-book / bug-report services. Run from this dir: `node build.mjs`.
//
// esbuild does NOT typecheck. Run `npx tsc -p tsconfig.json` (noEmit) before shipping a bundle.
//
// No external deps: the result store uses node:sqlite, so the bundle needs nothing from the box's
// node_modules and the service stays a single scp'd file.
//
// OUTPUT IS dist/server.mjs (untracked build artifact), scp'd to /srv/nasun/nasun-ai-host/server.mjs on the box.
// Resolves esbuild from the monorepo root node_modules (root has esbuild 0.27.x).

import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));

const banner = {
  js: '// GENERATED by build.mjs from src/*.ts -- do NOT edit by hand. Source of truth: src/.\n'
    + '// nasun-ai-host bundle. Rebuild: `node build.mjs`.\n'
    + "import { createRequire as __nodeCreateRequire } from 'node:module';\n"
    + 'const require = __nodeCreateRequire(import.meta.url);',
};

await build({
  entryPoints: [resolve(here, 'src/server.ts')],
  outfile: resolve(here, 'dist/server.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',  // node:sqlite (result store) needs 22; the box runs 22.x
  minify: false, // keep readable for box-side audit
  banner,
  legalComments: 'none',
  logLevel: 'info',
});
console.log('[build] wrote dist/server.mjs');
