[package]
name = "pado_prediction"
edition = "2024.beta"
version = "0.0.1"
# published-at will be set after deployment

[dependencies]
pado_tokens = { local = "../contracts" }

[addresses]
prediction = "0x0"
pado = "0xc84727af62147f35ccf070f521e441f48be9325ab0a1b56225f361f0bc266bb8"

[environments]
devnet = "56c8b101"
nasun-devnet = "56c8b101"
