[package]
name = "pado_prediction"
edition = "2024"
version = "0.0.1"
published-at = "0x98765cc3765324148db9815da8bce85e6ca895e94eed910b6cc9bec55cc22895"

[dependencies]
devnet_tokens = { local = "../../../packages/devnet-tokens" }

[addresses]
prediction = "0x0"

[environments]
devnet = "272218f1"
nasun-devnet = "272218f1"
