[package]
name = "pado_tokens"
edition = "2024"
version = "0.0.1"
## published-at set after deployment

[dependencies]
Sui = { local = "/home/naru/my_apps/nasun-devnet/sui/crates/sui-framework/packages/sui-framework" }

[addresses]
pado = "0x9984aab5fe518cf658532bf04e45b1eea075fe86ae62ad124bc3c8694f61dbb4"

[environments]
devnet = "56c8b101"
nasun-devnet = "56c8b101"