// Bundle src/server.ts -> dist/server.mjs (single self-contained ESM file, all deps inlined: hono,
// @hono/node-server, postgres). Preserves the box "scp one server.mjs" deploy contract used by the sibling
// identity-compute/identity/issuer services. Run from this dir: `node build.mjs`.
//
// OUTPUT IS dist/server.mjs (untracked build artifact). The deploy step scps dist/server.mjs to
// /srv/nasun/leaderboard/server.mjs on the box; the bundle is regenerable from src/ at any time.
//
// Resolves esbuild from the monorepo root node_modules (root has esbuild 0.27.x).

import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));

const banner = {
  // ESM output shim so any CJS dep doing a module-load `require('crypto')` etc. resolves (same shim the
  // identity-compute bundle uses; esbuild's __require stub delegates to this real createRequire).
  js: '// GENERATED by build.mjs from src/*.ts -- do NOT edit by hand. Source of truth: src/.\n'
    + '// nasun-leaderboard bundle. Rebuild: `node build.mjs`.\n'
    + "import { createRequire as __nodeCreateRequire } from 'node:module';\n"
    + 'const require = __nodeCreateRequire(import.meta.url);',
};

// Two entrypoints: the read service (server.mjs, systemd service) + the snapshot generator CLI
// (snapshot.mjs, systemd timer + validation). Both single self-contained ESM bundles.
const entries = [
  { in: 'src/server.ts', out: 'dist/server.mjs' },
  { in: 'src/snapshot-cli.ts', out: 'dist/snapshot.mjs' },
];

for (const e of entries) {
  await build({
    entryPoints: [resolve(here, e.in)],
    outfile: resolve(here, e.out),
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node20',
    minify: false, // keep readable for box-side audit
    banner,
    legalComments: 'none',
    logLevel: 'info',
  });
  console.log(`[build] wrote ${e.out}`);
}
