[package]
name = "pado_scratchcard"
edition = "2024"
version = "0.0.1"
published-at = "0x25ebed7be9ab897d0734ae1341d45052bc53fa2f6f14a4818db0505add28699e"

[dependencies]
devnet_tokens = { local = "../../../packages/devnet-tokens" }

[addresses]
scratchcard = "0x0"

[environments]
devnet = "272218f1"
nasun-devnet = "272218f1"
